acl.o: acl.c server.h fmacros.h config.h solarisfixes.h rio.h sds.h \
 connection.h ae.h monotonic.h atomicvar.h commands.h \
 ../deps/lua/src/lua.h ../deps/lua/src/luaconf.h dict.h mt19937-64.h \
 kvstore.h adlist.h zmalloc.h anet.h version.h util.h latency.h \
 sparkline.h quicklist.h rax.h redismodule.h zipmap.h ziplist.h sha1.h \
 endianconv.h crc64.h stream.h listpack.h rdb.h sha256.h
adlist.o: adlist.c adlist.h zmalloc.h
ae.o: ae.c ae.h monotonic.h fmacros.h anet.h redisassert.h config.h \
 zmalloc.h ae_select.c
anet.o: anet.c fmacros.h anet.h config.h util.h sds.h
aof.o: aof.c server.h fmacros.h config.h solarisfixes.h rio.h sds.h \
 connection.h ae.h monotonic.h atomicvar.h commands.h \
 ../deps/lua/src/lua.h ../deps/lua/src/luaconf.h dict.h mt19937-64.h \
 kvstore.h adlist.h zmalloc.h anet.h version.h util.h latency.h \
 sparkline.h quicklist.h rax.h redismodule.h zipmap.h ziplist.h sha1.h \
 endianconv.h crc64.h stream.h listpack.h rdb.h bio.h functions.h \
 script.h
bio.o: bio.c server.h fmacros.h config.h solarisfixes.h rio.h sds.h \
 connection.h ae.h monotonic.h atomicvar.h commands.h \
 ../deps/lua/src/lua.h ../deps/lua/src/luaconf.h dict.h mt19937-64.h \
 kvstore.h adlist.h zmalloc.h anet.h version.h util.h latency.h \
 sparkline.h quicklist.h rax.h redismodule.h zipmap.h ziplist.h sha1.h \
 endianconv.h crc64.h stream.h listpack.h rdb.h bio.h
bitops.o: bitops.c server.h fmacros.h config.h solarisfixes.h rio.h sds.h \
 connection.h ae.h monotonic.h atomicvar.h commands.h \
 ../deps/lua/src/lua.h ../deps/lua/src/luaconf.h dict.h mt19937-64.h \
 kvstore.h adlist.h zmalloc.h anet.h version.h util.h latency.h \
 sparkline.h quicklist.h rax.h redismodule.h zipmap.h ziplist.h sha1.h \
 endianconv.h crc64.h stream.h listpack.h rdb.h
blocked.o: blocked.c server.h fmacros.h config.h solarisfixes.h rio.h \
 sds.h connection.h ae.h monotonic.h atomicvar.h commands.h \
 ../deps/lua/src/lua.h ../deps/lua/src/luaconf.h dict.h mt19937-64.h \
 kvstore.h adlist.h zmalloc.h anet.h version.h util.h latency.h \
 sparkline.h quicklist.h rax.h redismodule.h zipmap.h ziplist.h sha1.h \
 endianconv.h crc64.h stream.h listpack.h rdb.h slowlog.h
call_reply.o: call_reply.c server.h fmacros.h config.h solarisfixes.h \
 rio.h sds.h connection.h ae.h monotonic.h atomicvar.h commands.h \
 ../deps/lua/src/lua.h ../deps/lua/src/luaconf.h dict.h mt19937-64.h \
 kvstore.h adlist.h zmalloc.h anet.h version.h util.h latency.h \
 sparkline.h quicklist.h rax.h redismodule.h zipmap.h ziplist.h sha1.h \
 endianconv.h crc64.h stream.h listpack.h rdb.h call_reply.h \
 resp_parser.h
childinfo.o: childinfo.c server.h fmacros.h config.h solarisfixes.h rio.h \
 sds.h connection.h ae.h monotonic.h atomicvar.h commands.h \
 ../deps/lua/src/lua.h ../deps/lua/src/luaconf.h dict.h mt19937-64.h \
 kvstore.h adlist.h zmalloc.h anet.h version.h util.h latency.h \
 sparkline.h quicklist.h rax.h redismodule.h zipmap.h ziplist.h sha1.h \
 endianconv.h crc64.h stream.h listpack.h rdb.h
cli_commands.o: cli_commands.c cli_commands.h commands.h commands.def
cli_common.o: cli_common.c fmacros.h cli_common.h \
 ../deps/hiredis/hiredis.h ../deps/hiredis/read.h ../deps/hiredis/sds.h \
 ../deps/hiredis/alloc.h ../deps/hiredis/sdscompat.h version.h \
 ../deps/hiredis/sds.h
cluster.o: cluster.c server.h fmacros.h config.h solarisfixes.h rio.h \
 sds.h connection.h ae.h monotonic.h atomicvar.h commands.h \
 ../deps/lua/src/lua.h ../deps/lua/src/luaconf.h dict.h mt19937-64.h \
 kvstore.h adlist.h zmalloc.h anet.h version.h util.h latency.h \
 sparkline.h quicklist.h rax.h redismodule.h zipmap.h ziplist.h sha1.h \
 endianconv.h crc64.h stream.h listpack.h rdb.h cluster.h
cluster_legacy.o: cluster_legacy.c server.h fmacros.h config.h \
 solarisfixes.h rio.h sds.h connection.h ae.h monotonic.h atomicvar.h \
 commands.h ../deps/lua/src/lua.h ../deps/lua/src/luaconf.h dict.h \
 mt19937-64.h kvstore.h adlist.h zmalloc.h anet.h version.h util.h \
 latency.h sparkline.h quicklist.h rax.h redismodule.h zipmap.h ziplist.h \
 sha1.h endianconv.h crc64.h stream.h listpack.h rdb.h cluster.h \
 cluster_legacy.h
commands.o: commands.c commands.h server.h fmacros.h config.h \
 solarisfixes.h rio.h sds.h connection.h ae.h monotonic.h atomicvar.h \
 ../deps/lua/src/lua.h ../deps/lua/src/luaconf.h dict.h mt19937-64.h \
 kvstore.h adlist.h zmalloc.h anet.h version.h util.h latency.h \
 sparkline.h quicklist.h rax.h redismodule.h zipmap.h ziplist.h sha1.h \
 endianconv.h crc64.h stream.h listpack.h rdb.h commands.def
config.o: config.c server.h fmacros.h config.h solarisfixes.h rio.h sds.h \
 connection.h ae.h monotonic.h atomicvar.h commands.h \
 ../deps/lua/src/lua.h ../deps/lua/src/luaconf.h dict.h mt19937-64.h \
 kvstore.h adlist.h zmalloc.h anet.h version.h util.h latency.h \
 sparkline.h quicklist.h rax.h redismodule.h zipmap.h ziplist.h sha1.h \
 endianconv.h crc64.h stream.h listpack.h rdb.h cluster.h bio.h
connection.o: connection.c server.h fmacros.h config.h solarisfixes.h \
 rio.h sds.h connection.h ae.h monotonic.h atomicvar.h commands.h \
 ../deps/lua/src/lua.h ../deps/lua/src/luaconf.h dict.h mt19937-64.h \
 kvstore.h adlist.h zmalloc.h anet.h version.h util.h latency.h \
 sparkline.h quicklist.h rax.h redismodule.h zipmap.h ziplist.h sha1.h \
 endianconv.h crc64.h stream.h listpack.h rdb.h
crc16.o: crc16.c server.h fmacros.h config.h solarisfixes.h rio.h sds.h \
 connection.h ae.h monotonic.h atomicvar.h commands.h \
 ../deps/lua/src/lua.h ../deps/lua/src/luaconf.h dict.h mt19937-64.h \
 kvstore.h adlist.h zmalloc.h anet.h version.h util.h latency.h \
 sparkline.h quicklist.h rax.h redismodule.h zipmap.h ziplist.h sha1.h \
 endianconv.h crc64.h stream.h listpack.h rdb.h
crc64.o: crc64.c crc64.h crcspeed.h
crcspeed.o: crcspeed.c crcspeed.h
db.o: db.c server.h fmacros.h config.h solarisfixes.h rio.h sds.h \
 connection.h ae.h monotonic.h atomicvar.h commands.h \
 ../deps/lua/src/lua.h ../deps/lua/src/luaconf.h dict.h mt19937-64.h \
 kvstore.h adlist.h zmalloc.h anet.h version.h util.h latency.h \
 sparkline.h quicklist.h rax.h redismodule.h zipmap.h ziplist.h sha1.h \
 endianconv.h crc64.h stream.h listpack.h rdb.h cluster.h script.h \
 functions.h bio.h
debug.o: debug.c server.h fmacros.h config.h solarisfixes.h rio.h sds.h \
 connection.h ae.h monotonic.h atomicvar.h commands.h \
 ../deps/lua/src/lua.h ../deps/lua/src/luaconf.h dict.h mt19937-64.h \
 kvstore.h adlist.h zmalloc.h anet.h version.h util.h latency.h \
 sparkline.h quicklist.h rax.h redismodule.h zipmap.h ziplist.h sha1.h \
 endianconv.h crc64.h stream.h listpack.h rdb.h bio.h \
 ../deps/fpconv/fpconv_dtoa.h cluster.h threads_mngr.h
defrag.o: defrag.c server.h fmacros.h config.h solarisfixes.h rio.h sds.h \
 connection.h ae.h monotonic.h atomicvar.h commands.h \
 ../deps/lua/src/lua.h ../deps/lua/src/luaconf.h dict.h mt19937-64.h \
 kvstore.h adlist.h zmalloc.h anet.h version.h util.h latency.h \
 sparkline.h quicklist.h rax.h redismodule.h zipmap.h ziplist.h sha1.h \
 endianconv.h crc64.h stream.h listpack.h rdb.h
dict.o: dict.c fmacros.h dict.h mt19937-64.h zmalloc.h redisassert.h \
 config.h monotonic.h
endianconv.o: endianconv.c
eval.o: eval.c server.h fmacros.h config.h solarisfixes.h rio.h sds.h \
 connection.h ae.h monotonic.h atomicvar.h commands.h \
 ../deps/lua/src/lua.h ../deps/lua/src/luaconf.h dict.h mt19937-64.h \
 kvstore.h adlist.h zmalloc.h anet.h version.h util.h latency.h \
 sparkline.h quicklist.h rax.h redismodule.h zipmap.h ziplist.h sha1.h \
 endianconv.h crc64.h stream.h listpack.h rdb.h rand.h cluster.h \
 resp_parser.h script_lua.h script.h ../deps/lua/src/lauxlib.h \
 ../deps/lua/src/lua.h ../deps/lua/src/lualib.h
evict.o: evict.c server.h fmacros.h config.h solarisfixes.h rio.h sds.h \
 connection.h ae.h monotonic.h atomicvar.h commands.h \
 ../deps/lua/src/lua.h ../deps/lua/src/luaconf.h dict.h mt19937-64.h \
 kvstore.h adlist.h zmalloc.h anet.h version.h util.h latency.h \
 sparkline.h quicklist.h rax.h redismodule.h zipmap.h ziplist.h sha1.h \
 endianconv.h crc64.h stream.h listpack.h rdb.h bio.h script.h
expire.o: expire.c server.h fmacros.h config.h solarisfixes.h rio.h sds.h \
 connection.h ae.h monotonic.h atomicvar.h commands.h \
 ../deps/lua/src/lua.h ../deps/lua/src/luaconf.h dict.h mt19937-64.h \
 kvstore.h adlist.h zmalloc.h anet.h version.h util.h latency.h \
 sparkline.h quicklist.h rax.h redismodule.h zipmap.h ziplist.h sha1.h \
 endianconv.h crc64.h stream.h listpack.h rdb.h
function_lua.o: function_lua.c functions.h server.h fmacros.h config.h \
 solarisfixes.h rio.h sds.h connection.h ae.h monotonic.h atomicvar.h \
 commands.h ../deps/lua/src/lua.h ../deps/lua/src/luaconf.h dict.h \
 mt19937-64.h kvstore.h adlist.h zmalloc.h anet.h version.h util.h \
 latency.h sparkline.h quicklist.h rax.h redismodule.h zipmap.h ziplist.h \
 sha1.h endianconv.h crc64.h stream.h listpack.h rdb.h script.h \
 script_lua.h ../deps/lua/src/lauxlib.h ../deps/lua/src/lua.h \
 ../deps/lua/src/lualib.h
functions.o: functions.c functions.h server.h fmacros.h config.h \
 solarisfixes.h rio.h sds.h connection.h ae.h monotonic.h atomicvar.h \
 commands.h ../deps/lua/src/lua.h ../deps/lua/src/luaconf.h dict.h \
 mt19937-64.h kvstore.h adlist.h zmalloc.h anet.h version.h util.h \
 latency.h sparkline.h quicklist.h rax.h redismodule.h zipmap.h ziplist.h \
 sha1.h endianconv.h crc64.h stream.h listpack.h rdb.h script.h
geo.o: geo.c geo.h server.h fmacros.h config.h solarisfixes.h rio.h sds.h \
 connection.h ae.h monotonic.h atomicvar.h commands.h \
 ../deps/lua/src/lua.h ../deps/lua/src/luaconf.h dict.h mt19937-64.h \
 kvstore.h adlist.h zmalloc.h anet.h version.h util.h latency.h \
 sparkline.h quicklist.h rax.h redismodule.h zipmap.h ziplist.h sha1.h \
 endianconv.h crc64.h stream.h listpack.h rdb.h geohash_helper.h \
 geohash.h debugmacro.h pqsort.h
geohash.o: geohash.c geohash.h
geohash_helper.o: geohash_helper.c fmacros.h geohash_helper.h geohash.h \
 debugmacro.h
hyperloglog.o: hyperloglog.c server.h fmacros.h config.h solarisfixes.h \
 rio.h sds.h connection.h ae.h monotonic.h atomicvar.h commands.h \
 ../deps/lua/src/lua.h ../deps/lua/src/luaconf.h dict.h mt19937-64.h \
 kvstore.h adlist.h zmalloc.h anet.h version.h util.h latency.h \
 sparkline.h quicklist.h rax.h redismodule.h zipmap.h ziplist.h sha1.h \
 endianconv.h crc64.h stream.h listpack.h rdb.h
intset.o: intset.c intset.h zmalloc.h endianconv.h config.h redisassert.h
kvstore.o: kvstore.c fmacros.h zmalloc.h kvstore.h dict.h mt19937-64.h \
 adlist.h redisassert.h config.h monotonic.h
latency.o: latency.c server.h fmacros.h config.h solarisfixes.h rio.h \
 sds.h connection.h ae.h monotonic.h atomicvar.h commands.h \
 ../deps/lua/src/lua.h ../deps/lua/src/luaconf.h dict.h mt19937-64.h \
 kvstore.h adlist.h zmalloc.h anet.h version.h util.h latency.h \
 sparkline.h quicklist.h rax.h redismodule.h zipmap.h ziplist.h sha1.h \
 endianconv.h crc64.h stream.h listpack.h rdb.h \
 ../deps/hdr_histogram/hdr_histogram.h
lazyfree.o: lazyfree.c server.h fmacros.h config.h solarisfixes.h rio.h \
 sds.h connection.h ae.h monotonic.h atomicvar.h commands.h \
 ../deps/lua/src/lua.h ../deps/lua/src/luaconf.h dict.h mt19937-64.h \
 kvstore.h adlist.h zmalloc.h anet.h version.h util.h latency.h \
 sparkline.h quicklist.h rax.h redismodule.h zipmap.h ziplist.h sha1.h \
 endianconv.h crc64.h stream.h listpack.h rdb.h bio.h functions.h \
 script.h cluster.h
listpack.o: listpack.c listpack.h listpack_malloc.h zmalloc.h \
 redisassert.h config.h util.h sds.h
localtime.o: localtime.c
logreqres.o: logreqres.c server.h fmacros.h config.h solarisfixes.h rio.h \
 sds.h connection.h ae.h monotonic.h atomicvar.h commands.h \
 ../deps/lua/src/lua.h ../deps/lua/src/luaconf.h dict.h mt19937-64.h \
 kvstore.h adlist.h zmalloc.h anet.h version.h util.h latency.h \
 sparkline.h quicklist.h rax.h redismodule.h zipmap.h ziplist.h sha1.h \
 endianconv.h crc64.h stream.h listpack.h rdb.h
lolwut.o: lolwut.c server.h fmacros.h config.h solarisfixes.h rio.h sds.h \
 connection.h ae.h monotonic.h atomicvar.h commands.h \
 ../deps/lua/src/lua.h ../deps/lua/src/luaconf.h dict.h mt19937-64.h \
 kvstore.h adlist.h zmalloc.h anet.h version.h util.h latency.h \
 sparkline.h quicklist.h rax.h redismodule.h zipmap.h ziplist.h sha1.h \
 endianconv.h crc64.h stream.h listpack.h rdb.h lolwut.h
lolwut5.o: lolwut5.c server.h fmacros.h config.h solarisfixes.h rio.h \
 sds.h connection.h ae.h monotonic.h atomicvar.h commands.h \
 ../deps/lua/src/lua.h ../deps/lua/src/luaconf.h dict.h mt19937-64.h \
 kvstore.h adlist.h zmalloc.h anet.h version.h util.h latency.h \
 sparkline.h quicklist.h rax.h redismodule.h zipmap.h ziplist.h sha1.h \
 endianconv.h crc64.h stream.h listpack.h rdb.h lolwut.h
lolwut6.o: lolwut6.c server.h fmacros.h config.h solarisfixes.h rio.h \
 sds.h connection.h ae.h monotonic.h atomicvar.h commands.h \
 ../deps/lua/src/lua.h ../deps/lua/src/luaconf.h dict.h mt19937-64.h \
 kvstore.h adlist.h zmalloc.h anet.h version.h util.h latency.h \
 sparkline.h quicklist.h rax.h redismodule.h zipmap.h ziplist.h sha1.h \
 endianconv.h crc64.h stream.h listpack.h rdb.h lolwut.h
lzf_c.o: lzf_c.c lzfP.h
lzf_d.o: lzf_d.c lzfP.h
memtest.o: memtest.c config.h redisassert.h
module.o: module.c server.h fmacros.h config.h solarisfixes.h rio.h sds.h \
 connection.h ae.h monotonic.h atomicvar.h commands.h \
 ../deps/lua/src/lua.h ../deps/lua/src/luaconf.h dict.h mt19937-64.h \
 kvstore.h adlist.h zmalloc.h anet.h version.h util.h latency.h \
 sparkline.h quicklist.h rax.h redismodule.h zipmap.h ziplist.h sha1.h \
 endianconv.h crc64.h stream.h listpack.h rdb.h cluster.h slowlog.h \
 script.h call_reply.h resp_parser.h \
 ../deps/hdr_histogram/hdr_histogram.h crc16_slottable.h
monotonic.o: monotonic.c monotonic.h fmacros.h redisassert.h config.h
mt19937-64.o: mt19937-64.c mt19937-64.h
multi.o: multi.c server.h fmacros.h config.h solarisfixes.h rio.h sds.h \
 connection.h ae.h monotonic.h atomicvar.h commands.h \
 ../deps/lua/src/lua.h ../deps/lua/src/luaconf.h dict.h mt19937-64.h \
 kvstore.h adlist.h zmalloc.h anet.h version.h util.h latency.h \
 sparkline.h quicklist.h rax.h redismodule.h zipmap.h ziplist.h sha1.h \
 endianconv.h crc64.h stream.h listpack.h rdb.h
networking.o: networking.c server.h fmacros.h config.h solarisfixes.h \
 rio.h sds.h connection.h ae.h monotonic.h atomicvar.h commands.h \
 ../deps/lua/src/lua.h ../deps/lua/src/luaconf.h dict.h mt19937-64.h \
 kvstore.h adlist.h zmalloc.h anet.h version.h util.h latency.h \
 sparkline.h quicklist.h rax.h redismodule.h zipmap.h ziplist.h sha1.h \
 endianconv.h crc64.h stream.h listpack.h rdb.h cluster.h script.h \
 ../deps/fpconv/fpconv_dtoa.h fmtargs.h
notify.o: notify.c server.h fmacros.h config.h solarisfixes.h rio.h sds.h \
 connection.h ae.h monotonic.h atomicvar.h commands.h \
 ../deps/lua/src/lua.h ../deps/lua/src/luaconf.h dict.h mt19937-64.h \
 kvstore.h adlist.h zmalloc.h anet.h version.h util.h latency.h \
 sparkline.h quicklist.h rax.h redismodule.h zipmap.h ziplist.h sha1.h \
 endianconv.h crc64.h stream.h listpack.h rdb.h
object.o: object.c server.h fmacros.h config.h solarisfixes.h rio.h sds.h \
 connection.h ae.h monotonic.h atomicvar.h commands.h \
 ../deps/lua/src/lua.h ../deps/lua/src/luaconf.h dict.h mt19937-64.h \
 kvstore.h adlist.h zmalloc.h anet.h version.h util.h latency.h \
 sparkline.h quicklist.h rax.h redismodule.h zipmap.h ziplist.h sha1.h \
 endianconv.h crc64.h stream.h listpack.h rdb.h functions.h script.h \
 intset.h
pqsort.o: pqsort.c
pubsub.o: pubsub.c server.h fmacros.h config.h solarisfixes.h rio.h sds.h \
 connection.h ae.h monotonic.h atomicvar.h commands.h \
 ../deps/lua/src/lua.h ../deps/lua/src/luaconf.h dict.h mt19937-64.h \
 kvstore.h adlist.h zmalloc.h anet.h version.h util.h latency.h \
 sparkline.h quicklist.h rax.h redismodule.h zipmap.h ziplist.h sha1.h \
 endianconv.h crc64.h stream.h listpack.h rdb.h cluster.h
quicklist.o: quicklist.c quicklist.h zmalloc.h config.h listpack.h util.h \
 sds.h lzf.h redisassert.h
rand.o: rand.c
rax.o: rax.c rax.h redisassert.h config.h rax_malloc.h zmalloc.h
rdb.o: rdb.c server.h fmacros.h config.h solarisfixes.h rio.h sds.h \
 connection.h ae.h monotonic.h atomicvar.h commands.h \
 ../deps/lua/src/lua.h ../deps/lua/src/luaconf.h dict.h mt19937-64.h \
 kvstore.h adlist.h zmalloc.h anet.h version.h util.h latency.h \
 sparkline.h quicklist.h rax.h redismodule.h zipmap.h ziplist.h sha1.h \
 endianconv.h crc64.h stream.h listpack.h rdb.h lzf.h \
 ../deps/fpconv/fpconv_dtoa.h functions.h script.h intset.h bio.h
redis-benchmark.o: redis-benchmark.c fmacros.h \
 ../deps/hiredis/sdscompat.h ../deps/hiredis/sds.h ae.h monotonic.h \
 ../deps/hiredis/hiredis.h ../deps/hiredis/read.h ../deps/hiredis/sds.h \
 ../deps/hiredis/alloc.h adlist.h dict.h mt19937-64.h zmalloc.h \
 atomicvar.h config.h crc16_slottable.h \
 ../deps/hdr_histogram/hdr_histogram.h cli_common.h
redis-check-aof.o: redis-check-aof.c server.h fmacros.h config.h \
 solarisfixes.h rio.h sds.h connection.h ae.h monotonic.h atomicvar.h \
 commands.h ../deps/lua/src/lua.h ../deps/lua/src/luaconf.h dict.h \
 mt19937-64.h kvstore.h adlist.h zmalloc.h anet.h version.h util.h \
 latency.h sparkline.h quicklist.h rax.h redismodule.h zipmap.h ziplist.h \
 sha1.h endianconv.h crc64.h stream.h listpack.h rdb.h
redis-check-rdb.o: redis-check-rdb.c mt19937-64.h server.h fmacros.h \
 config.h solarisfixes.h rio.h sds.h connection.h ae.h monotonic.h \
 atomicvar.h commands.h ../deps/lua/src/lua.h ../deps/lua/src/luaconf.h \
 dict.h kvstore.h adlist.h zmalloc.h anet.h version.h util.h latency.h \
 sparkline.h quicklist.h rax.h redismodule.h zipmap.h ziplist.h sha1.h \
 endianconv.h crc64.h stream.h listpack.h rdb.h
redis-cli.o: redis-cli.c fmacros.h ../deps/hiredis/hiredis.h \
 ../deps/hiredis/read.h ../deps/hiredis/sds.h ../deps/hiredis/alloc.h \
 ../deps/hiredis/sdscompat.h ../deps/hiredis/sds.h dict.h mt19937-64.h \
 adlist.h zmalloc.h ../deps/linenoise/linenoise.h anet.h ae.h monotonic.h \
 connection.h cli_common.h cli_commands.h commands.h
redisassert.o: redisassert.c
replication.o: replication.c server.h fmacros.h config.h solarisfixes.h \
 rio.h sds.h connection.h ae.h monotonic.h atomicvar.h commands.h \
 ../deps/lua/src/lua.h ../deps/lua/src/luaconf.h dict.h mt19937-64.h \
 kvstore.h adlist.h zmalloc.h anet.h version.h util.h latency.h \
 sparkline.h quicklist.h rax.h redismodule.h zipmap.h ziplist.h sha1.h \
 endianconv.h crc64.h stream.h listpack.h rdb.h cluster.h bio.h \
 functions.h script.h
resp_parser.o: resp_parser.c resp_parser.h server.h fmacros.h config.h \
 solarisfixes.h rio.h sds.h connection.h ae.h monotonic.h atomicvar.h \
 commands.h ../deps/lua/src/lua.h ../deps/lua/src/luaconf.h dict.h \
 mt19937-64.h kvstore.h adlist.h zmalloc.h anet.h version.h util.h \
 latency.h sparkline.h quicklist.h rax.h redismodule.h zipmap.h ziplist.h \
 sha1.h endianconv.h crc64.h stream.h listpack.h rdb.h
rio.o: rio.c fmacros.h ../deps/fpconv/fpconv_dtoa.h rio.h sds.h \
 connection.h ae.h monotonic.h util.h crc64.h config.h server.h \
 solarisfixes.h atomicvar.h commands.h ../deps/lua/src/lua.h \
 ../deps/lua/src/luaconf.h dict.h mt19937-64.h kvstore.h adlist.h \
 zmalloc.h anet.h version.h latency.h sparkline.h quicklist.h rax.h \
 redismodule.h zipmap.h ziplist.h sha1.h endianconv.h stream.h listpack.h \
 rdb.h
script.o: script.c server.h fmacros.h config.h solarisfixes.h rio.h sds.h \
 connection.h ae.h monotonic.h atomicvar.h commands.h \
 ../deps/lua/src/lua.h ../deps/lua/src/luaconf.h dict.h mt19937-64.h \
 kvstore.h adlist.h zmalloc.h anet.h version.h util.h latency.h \
 sparkline.h quicklist.h rax.h redismodule.h zipmap.h ziplist.h sha1.h \
 endianconv.h crc64.h stream.h listpack.h rdb.h script.h cluster.h \
 ../deps/lua/src/lauxlib.h ../deps/lua/src/lua.h
script_lua.o: script_lua.c script_lua.h server.h fmacros.h config.h \
 solarisfixes.h rio.h sds.h connection.h ae.h monotonic.h atomicvar.h \
 commands.h ../deps/lua/src/lua.h ../deps/lua/src/luaconf.h dict.h \
 mt19937-64.h kvstore.h adlist.h zmalloc.h anet.h version.h util.h \
 latency.h sparkline.h quicklist.h rax.h redismodule.h zipmap.h ziplist.h \
 sha1.h endianconv.h crc64.h stream.h listpack.h rdb.h script.h \
 ../deps/lua/src/lauxlib.h ../deps/lua/src/lua.h ../deps/lua/src/lualib.h \
 ../deps/fpconv/fpconv_dtoa.h rand.h cluster.h resp_parser.h
sds.o: sds.c redisassert.h config.h sds.h sdsalloc.h zmalloc.h util.h
sentinel.o: sentinel.c server.h fmacros.h config.h solarisfixes.h rio.h \
 sds.h connection.h ae.h monotonic.h atomicvar.h commands.h \
 ../deps/lua/src/lua.h ../deps/lua/src/luaconf.h dict.h mt19937-64.h \
 kvstore.h adlist.h zmalloc.h anet.h version.h util.h latency.h \
 sparkline.h quicklist.h rax.h redismodule.h zipmap.h ziplist.h sha1.h \
 endianconv.h crc64.h stream.h listpack.h rdb.h ../deps/hiredis/hiredis.h \
 ../deps/hiredis/read.h ../deps/hiredis/sds.h ../deps/hiredis/alloc.h \
 ../deps/hiredis/async.h ../deps/hiredis/hiredis.h
server.o: server.c server.h fmacros.h config.h solarisfixes.h rio.h sds.h \
 connection.h ae.h monotonic.h atomicvar.h commands.h \
 ../deps/lua/src/lua.h ../deps/lua/src/luaconf.h dict.h mt19937-64.h \
 kvstore.h adlist.h zmalloc.h anet.h version.h util.h latency.h \
 sparkline.h quicklist.h rax.h redismodule.h zipmap.h ziplist.h sha1.h \
 endianconv.h crc64.h stream.h listpack.h rdb.h cluster.h slowlog.h bio.h \
 functions.h script.h ../deps/hdr_histogram/hdr_histogram.h syscheck.h \
 threads_mngr.h fmtargs.h asciilogo.h
setcpuaffinity.o: setcpuaffinity.c config.h
setproctitle.o: setproctitle.c
sha1.o: sha1.c solarisfixes.h sha1.h config.h
sha256.o: sha256.c sha256.h
siphash.o: siphash.c
slowlog.o: slowlog.c server.h fmacros.h config.h solarisfixes.h rio.h \
 sds.h connection.h ae.h monotonic.h atomicvar.h commands.h \
 ../deps/lua/src/lua.h ../deps/lua/src/luaconf.h dict.h mt19937-64.h \
 kvstore.h adlist.h zmalloc.h anet.h version.h util.h latency.h \
 sparkline.h quicklist.h rax.h redismodule.h zipmap.h ziplist.h sha1.h \
 endianconv.h crc64.h stream.h listpack.h rdb.h slowlog.h
socket.o: socket.c server.h fmacros.h config.h solarisfixes.h rio.h sds.h \
 connection.h ae.h monotonic.h atomicvar.h commands.h \
 ../deps/lua/src/lua.h ../deps/lua/src/luaconf.h dict.h mt19937-64.h \
 kvstore.h adlist.h zmalloc.h anet.h version.h util.h latency.h \
 sparkline.h quicklist.h rax.h redismodule.h zipmap.h ziplist.h sha1.h \
 endianconv.h crc64.h stream.h listpack.h rdb.h connhelpers.h
sort.o: sort.c server.h fmacros.h config.h solarisfixes.h rio.h sds.h \
 connection.h ae.h monotonic.h atomicvar.h commands.h \
 ../deps/lua/src/lua.h ../deps/lua/src/luaconf.h dict.h mt19937-64.h \
 kvstore.h adlist.h zmalloc.h anet.h version.h util.h latency.h \
 sparkline.h quicklist.h rax.h redismodule.h zipmap.h ziplist.h sha1.h \
 endianconv.h crc64.h stream.h listpack.h rdb.h pqsort.h cluster.h
sparkline.o: sparkline.c server.h fmacros.h config.h solarisfixes.h rio.h \
 sds.h connection.h ae.h monotonic.h atomicvar.h commands.h \
 ../deps/lua/src/lua.h ../deps/lua/src/luaconf.h dict.h mt19937-64.h \
 kvstore.h adlist.h zmalloc.h anet.h version.h util.h latency.h \
 sparkline.h quicklist.h rax.h redismodule.h zipmap.h ziplist.h sha1.h \
 endianconv.h crc64.h stream.h listpack.h rdb.h
strl.o: strl.c
syncio.o: syncio.c server.h fmacros.h config.h solarisfixes.h rio.h sds.h \
 connection.h ae.h monotonic.h atomicvar.h commands.h \
 ../deps/lua/src/lua.h ../deps/lua/src/luaconf.h dict.h mt19937-64.h \
 kvstore.h adlist.h zmalloc.h anet.h version.h util.h latency.h \
 sparkline.h quicklist.h rax.h redismodule.h zipmap.h ziplist.h sha1.h \
 endianconv.h crc64.h stream.h listpack.h rdb.h
syscheck.o: syscheck.c fmacros.h config.h syscheck.h sds.h anet.h
t_hash.o: t_hash.c server.h fmacros.h config.h solarisfixes.h rio.h sds.h \
 connection.h ae.h monotonic.h atomicvar.h commands.h \
 ../deps/lua/src/lua.h ../deps/lua/src/luaconf.h dict.h mt19937-64.h \
 kvstore.h adlist.h zmalloc.h anet.h version.h util.h latency.h \
 sparkline.h quicklist.h rax.h redismodule.h zipmap.h ziplist.h sha1.h \
 endianconv.h crc64.h stream.h listpack.h rdb.h
t_list.o: t_list.c server.h fmacros.h config.h solarisfixes.h rio.h sds.h \
 connection.h ae.h monotonic.h atomicvar.h commands.h \
 ../deps/lua/src/lua.h ../deps/lua/src/luaconf.h dict.h mt19937-64.h \
 kvstore.h adlist.h zmalloc.h anet.h version.h util.h latency.h \
 sparkline.h quicklist.h rax.h redismodule.h zipmap.h ziplist.h sha1.h \
 endianconv.h crc64.h stream.h listpack.h rdb.h
t_set.o: t_set.c server.h fmacros.h config.h solarisfixes.h rio.h sds.h \
 connection.h ae.h monotonic.h atomicvar.h commands.h \
 ../deps/lua/src/lua.h ../deps/lua/src/luaconf.h dict.h mt19937-64.h \
 kvstore.h adlist.h zmalloc.h anet.h version.h util.h latency.h \
 sparkline.h quicklist.h rax.h redismodule.h zipmap.h ziplist.h sha1.h \
 endianconv.h crc64.h stream.h listpack.h rdb.h intset.h
t_stream.o: t_stream.c server.h fmacros.h config.h solarisfixes.h rio.h \
 sds.h connection.h ae.h monotonic.h atomicvar.h commands.h \
 ../deps/lua/src/lua.h ../deps/lua/src/luaconf.h dict.h mt19937-64.h \
 kvstore.h adlist.h zmalloc.h anet.h version.h util.h latency.h \
 sparkline.h quicklist.h rax.h redismodule.h zipmap.h ziplist.h sha1.h \
 endianconv.h crc64.h stream.h listpack.h rdb.h
t_string.o: t_string.c server.h fmacros.h config.h solarisfixes.h rio.h \
 sds.h connection.h ae.h monotonic.h atomicvar.h commands.h \
 ../deps/lua/src/lua.h ../deps/lua/src/luaconf.h dict.h mt19937-64.h \
 kvstore.h adlist.h zmalloc.h anet.h version.h util.h latency.h \
 sparkline.h quicklist.h rax.h redismodule.h zipmap.h ziplist.h sha1.h \
 endianconv.h crc64.h stream.h listpack.h rdb.h
t_zset.o: t_zset.c server.h fmacros.h config.h solarisfixes.h rio.h sds.h \
 connection.h ae.h monotonic.h atomicvar.h commands.h \
 ../deps/lua/src/lua.h ../deps/lua/src/luaconf.h dict.h mt19937-64.h \
 kvstore.h adlist.h zmalloc.h anet.h version.h util.h latency.h \
 sparkline.h quicklist.h rax.h redismodule.h zipmap.h ziplist.h sha1.h \
 endianconv.h crc64.h stream.h listpack.h rdb.h intset.h
threads_mngr.o: threads_mngr.c threads_mngr.h fmacros.h
timeout.o: timeout.c server.h fmacros.h config.h solarisfixes.h rio.h \
 sds.h connection.h ae.h monotonic.h atomicvar.h commands.h \
 ../deps/lua/src/lua.h ../deps/lua/src/luaconf.h dict.h mt19937-64.h \
 kvstore.h adlist.h zmalloc.h anet.h version.h util.h latency.h \
 sparkline.h quicklist.h rax.h redismodule.h zipmap.h ziplist.h sha1.h \
 endianconv.h crc64.h stream.h listpack.h rdb.h cluster.h
tls.o: tls.c server.h fmacros.h config.h solarisfixes.h rio.h sds.h \
 connection.h ae.h monotonic.h atomicvar.h commands.h \
 ../deps/lua/src/lua.h ../deps/lua/src/luaconf.h dict.h mt19937-64.h \
 kvstore.h adlist.h zmalloc.h anet.h version.h util.h latency.h \
 sparkline.h quicklist.h rax.h redismodule.h zipmap.h ziplist.h sha1.h \
 endianconv.h crc64.h stream.h listpack.h rdb.h connhelpers.h
tracking.o: tracking.c server.h fmacros.h config.h solarisfixes.h rio.h \
 sds.h connection.h ae.h monotonic.h atomicvar.h commands.h \
 ../deps/lua/src/lua.h ../deps/lua/src/luaconf.h dict.h mt19937-64.h \
 kvstore.h adlist.h zmalloc.h anet.h version.h util.h latency.h \
 sparkline.h quicklist.h rax.h redismodule.h zipmap.h ziplist.h sha1.h \
 endianconv.h crc64.h stream.h listpack.h rdb.h
unix.o: unix.c server.h fmacros.h config.h solarisfixes.h rio.h sds.h \
 connection.h ae.h monotonic.h atomicvar.h commands.h \
 ../deps/lua/src/lua.h ../deps/lua/src/luaconf.h dict.h mt19937-64.h \
 kvstore.h adlist.h zmalloc.h anet.h version.h util.h latency.h \
 sparkline.h quicklist.h rax.h redismodule.h zipmap.h ziplist.h sha1.h \
 endianconv.h crc64.h stream.h listpack.h rdb.h
util.o: util.c fmacros.h ../deps/fpconv/fpconv_dtoa.h util.h sds.h \
 sha256.h config.h
ziplist.o: ziplist.c zmalloc.h util.h sds.h ziplist.h config.h \
 endianconv.h redisassert.h
zipmap.o: zipmap.c zmalloc.h endianconv.h config.h
zmalloc.o: zmalloc.c fmacros.h config.h solarisfixes.h zmalloc.h \
 atomicvar.h
