#define REDIS_GIT_SHA1 "e92363e2"
#define REDIS_GIT_DIRTY "13"
#define REDIS_BUILD_ID "al-s-1716556708"
#include "version.h"
#define REDIS_BUILD_ID_RAW REDIS_VERSION REDIS_BUILD_ID REDIS_GIT_DIRTY REDIS_GIT_SHA1
